# ARC training config

defaults:
  - arch: srm
  - _self_

hydra:
  output_subdir: null

entity: "trelis"

# Data path
data_paths: null
data_paths_test: []

load_checkpoint: null
checkpoint_path: null

evaluators:
  - name: arc@ARC

# Hyperparams - Training
global_batch_size: 128

epochs: 25000
eval_interval: 10
checkpoint_every_eval: True
checkpoint_every_n_steps: null
halt_max_steps_eval: null
puzzle_emb_reinit_strategy: "mean"

lr: 0.25e-4
lr_min_ratio: 1.0
lr_warmup_steps: 2000

# Standard hyperparameter settings for LM, as used in Llama
beta1: 0.9
beta2: 0.95
weight_decay: 0.1
puzzle_emb_weight_decay: 1e-5

# Hyperparams - Puzzle embeddings training
puzzle_emb_lr: 1.25e-3
shared_puzzle_emb_lr: 0.75e-4
shared_puzzle_emb_weight_decay: 1e-4

seed: 0
min_eval_interval: 0 # when to start the eval

ema: True # use Exponential-Moving-Average
ema_rate: 0.999
freeze_weights: False
freeze_weights_epochs: null
